spring:
  profiles:
    active: local
logging:
  level:
    root: info


---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  batch:
    jdbc:
      initialize-schema: always
      isolation-level-for-create: default


---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '0000'

  batch:
    jdbc:
      initialize-schema: embedded
      isolation-level-for-create: default
    job:
      names: ${job.name:NONE}

---
spring:
  config:
    activate:
      on-profile: training
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '0000'

  batch:
    jdbc:
      initialize-schema: embedded
      isolation-level-for-create: default
    job:
      names: ${job.name:NONE}