spring:
  profiles:
    active: mysql
logging:
  level:
    root: info


---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  batch:
    jdbc:
      initialize-schema: always
      isolation-level-for-create: default


---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '0000'

  batch:
    jdbc:
      initialize-schema: embedded
      isolation-level-for-create: default
    job:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: training
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '0000'

  batch:
    jdbc:
      initialize-schema: embedded
      isolation-level-for-create: default
    job:
      names: ${job.name:NONE}

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://docker_batch_db:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '0000'
  batch:
    jdbc:
      initialize-schema: embedded
      isolation-level-for-create: default
    job:
      names: ${job.name:NONE}

---
spring:
  config:
    activate:
      on-profile: double
  db1:
    datasource:
      url: jdbc:mysql://localhost:3306/test
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: '0000'
    jpa:
      show-sql: true
    hibernate:
      ddl-auto: update
  db2:
    datasource:
      url: jdbc:mysql://localhost:3307/test2
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: '000'
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
    hibernate:
      ddl-auto: create


  batch:
    jdbc:
      initialize-schema: embedded
      isolation-level-for-create: default
    job:
      names: ${job.name:NONE}
