spring:
  datasource:
    url: jdbc:h2:mem:abc
    driver-class-name: org.h2.Driver
    username: sa
    password:
  batch:
    jdbc:
      initialize-schema: embedded
      isolation-level-for-create: default
    job:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: create