spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '0000'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always

logging:
  level:
    optimization.reader: DEBUG